name: Clang Format
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      BUILDDIR: build
    steps:
      - name: Setup GitHub actions
        uses: actions/checkout@v3
      - name: Run clang-format
        id: run_clang-format
        run: |
          clang-format --dry-run --Werror  **/*.{cpp,hpp}
