name: Ubuntu Build
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        compiler: [ gcc-10, clang-12 ]
    name: "${{ matrix.compiler }}"
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - name: Setup Github actions
        uses: actions/checkout@v3
      - name: Build x86 emulator
        id: build_emulator
        run: |
          cmake -B build &&
          cmake --build build
      - name: Run the tests
        id: run_tests
        run: ctest --test-dir build --parallel
  coverage:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      CC: gcc-10
    steps:
      - name: Install lcov
        id: install_lcov
        run: sudo apt install lcov
      - name: Generate coverage report
        id: generate_cov
        run: |
          lcov --directory . --capture --output-file coverage.info
      - name: Generate Codecov Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.info
